ShiYue_Channel=95
ShiYueSERVER_URL=http://sdk.shiyuegame.com/
ShiYue_PAY_PUBLICKEY=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC20AP4+zExpVfhJWhJPHIaoNymZ6Z8sLSftW5QExU1XVbZNtQ/WJtiJ6+qUVK2A2nhny56MPI2CQ4HzkcbGK+Be8eD7a4ADwfO6hWQhsdk6uA4i25zAsQaLsoDqAsiWVFpkvjxhNDjnprw3M2Wnu/CpFDkgQgdGWc0+Ym9sTH1exyNqZEI3A1TobtBkt6F84Q+UAr8i+j5aYvT2BDkGclrBbw6ckbNVPOsz0fYU7Ik81IO6UP298uNjEMhJwfWGpWaB4JDYcHveQZm6JOgw5goIPHcFVXpWvI6kFWH0aWJ7qGBhF0nymM8J+EX10CH6McX/1WrGEOVbIeIN107AUDJAgMBAAECggEBAKm8T8Pv7kgLHaIUqlQ9RDBHJTd3y1PAeaRDv02nuixXIpkBWGYMbhDfijGX2jTWzItI0c1v/qN/GsDSnKCi9elCNQfgOYsiaXyLSURsb1va3B6EDyPH8K3ivXxRnSziQz3D0VHloFGG5JM4X8Y2gaR2DglraE4kVPgRrPssN5eUiNR3FUoyu2ACjZnP0y4D9hEajRl9ZIJ8dL1a3TLxKpplqsWcuxbTVbL6Ckku2q/Mz6NWLsWA3VzZ2Xpr41qvFEezZfJabE2NF08mkRx92B2xYDKWUkazqxEAn47caJ51ctUNZHCGBUbxJxDnx+4xgBh1Ti5rPcr6eE25NPwScEUCgYEA60/rfV+a1ce3ZPTz/j19Kn70g/Iu94BTAtVBvKgDbVNkwGmMDAjoVWoJvXzpsw08T8dfkSw+37CtHPYdvliO3NW8YqPc3dwuQyS+ij95A02Y96WTX7wxln75+o3teH9zeZH2QxtzHEH0Xmsj5WhsrQYAbHgQGIyhqMeQ3MraiRMCgYEAxuKBxL8pRZHsaJ2aGvGeNny5/U2KYEkGnlvuv4JS7XWG2jiKPeY1w2vQN5FxBd4Zqyli10GmtHsyqvLJC4iiTCGLxITF1W4wk/6V48Fg19MkMFVrZSbyplOgSCfUREkyUiKrvBhFOr9TIq0KwofAqyQTij/pkZc8jvE+sApohjMCgYBmVk2eKvQVwVPbDkUG7wr+blQ9Bhiy/xYbB1AdkhxbcYdBvyVvHnicnQ87X5XrjvgJ4jWH12xIsHe5PrhUzgLju/jAFW+69UURYmuTiGNCsn6yRUpAuoH+Z56j/xGl9BfuaTJmoQuA4JY8cfAclzucTB3nDphBdPfhhVlVDMvaDQKBgQCAbBY7QuyVfapXyxyNNWNh75vxUjZ+AemCK/64LqD5sCAJnOS3H4Wr0Fw85W9DyKxud2TZdgz9EWggNnFXPzz9R9QGa22LaYF4rrV+wYmVE0OU6jNUt5eLiwg+T2mjRlh17OlTpaBeVNiL1YzTG/FvEPaFGMvrNOrnqiM+bRodPQKBgBAJYIO/rj0Z0R42ia24AGuSPHZ5pmSkNrYEqxthITRMWP7cG70dxN22WK/wgrDMLqqGIQ+X287QJUECYkYDWvg113z45tAmr3KjDbTZ9gCWJ2adClrUn6zRc8VpCju+hQ/Gjbs+l8iS5BhFvCYQRpVAs/8uE/7WQYqq9xQdMVVw
ShiYue_Sub_Channel=1
ShiYue_Channel_Dealer_Id=11
BURIED_LOG_REPORT_OPEN=false
BURIED_LOG_REPORT_URL=https://sdk-upload.shiyuegame.com/user/entry
SCREEN_ORIENTATION=PORTRAIT
ShiYue_Channel_Dealer=shiyue
LeLanWechatAppId=100
U8_SDK_VERSION_CODE=205080
U8_Channel=189
U8_APPID=17
U8_APPKEY=746355d018d57ce509b6dfe6df268740
U8_SDK_SHOW_SPLASH=false
U8SERVER_URL=http://192.168.2.88
U8_ANALYTICS=false
