SHIYUE_APPID=17
SHIYUE_CHANNEL=95
SHIYUE_SUB_CHANNEL=53
SHIYUE_CHANNEL_DEALER=shiyue
SHIYUE_CHANNEL_DEALER_ID=11
SHIYUE_SERVER_URL=https://sdk.shiyuegame.com/
EFFECT_PROJECT_ID=6
SCREEN_ORIENTATION=PORTRAIT
LeLanAliSecret=BpiRfa9IvJkF25qzKJwgA67a8XRINFClvS34+N9m78778mM+ng2SR3UtDTPueCWReb7K0yL1looEWcHeB9WfNdTA29elHf5DcSPCScNPWc89qDZ5LJYwYF6j+8LmDKDePHQd89Wcn8B+idC7d1aL6gczc6Gc5oaQqjxSaHmCvxV3usCW+I/MlVrAPNGnegBNr7N5ljCVYJSE4vZ1WJcEsDK3jE/E3LCsJe6Zc+lxIs/dM5WdGTLnHubeo5lWhUsrV+zAlBH6S5P4t4IeVaAQi95GoT3Xt9klo/jiLl/DNa4=
LeLanAppId=2139
LeLanProjectId=107
LeLanPublicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxioBBAyhF7sCRYCVT+VxH5PtlwjumZQ4Ahna7e4HLVWIM620JnCHgxhFOESl10IfT/nwSrk8EwP4Hzh7El791xZu4we192kmkXGw4FGSpieKJYUESHEYdggQYchzhvh1XZx6P6wzudnIgMb8K0nkkI0+DSRYXkw2fu0UQf4fLByIgAHnoRENuhxlfKEfWqyVg8mxB0v7YfThA+FmBh8VMHESWwnc7Vk2St86aOvRE5hO6CE4S10aJS4DQrjbhXPBuSfXJdVy5FHBCrEBjSe95/mRVY/X8NIg/8V5NAH/p9dAV6T6dq5/EJ+pSIGsfU3QS9vWWQch35/cJEByExFbzQIDAQAB
LeLanQqAppid=0
LeLanSecret=P1E7rkG0vKBcjEcYF2PAleFy
LeLanWechatAppId=0
MomoyuAppId=0
MomoyuScheme=0
RH_SDK_VERSION_CODE=200000
RH_SDK_VERSION_NAME=2.0.0
SHOW_AGGREEMENT=True
TapTapAppId=0
CHANNEL_SDK_VERSION_CODE=704060
CHANNEL_SDK_VERSION_NAME=7.4.6
SHIYUE_SDK_VERSION_CODE=704060
SHIYUE_SDK_VERSION_NAME=7.4.6